name: study_stats
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  provider: ^6.1.2
  path_provider: ^2.1.2
  hive_flutter: ^1.1.0
  # google_fonts: ^6.2.0
  smooth_page_indicator: ^1.1.0
  firebase_core: ^2.25.5
  firebase_storage: ^11.6.7
  cloud_firestore: ^4.15.6
  timezone: ^0.9.2
  flutter_dropdown: ^1.0.1+hotfix.1
  dialog_alert: ^0.0.3
  top_snackbar_flutter: ^3.1.0
  loading_animation_widget: ^1.2.0+4
  image_picker: ^1.0.7
  share_plus: ^7.2.2
  permission_handler: ^11.3.0
  screenshot: ^2.1.0
  mrx_charts: ^0.1.3
  awesome_circular_chart: ^1.0.0
  dotted_border: ^2.1.0
  chart_sparkline: ^1.0.15+1
  cloudinary: ^1.2.0
  intl: ^0.19.0
  flutter_local_notifications: ^16.3.2
  tutorial_coach_mark: ^1.2.11
  flutter_slidable: ^3.0.1
  simple_circular_progress_bar: ^1.0.2
  flutter_launcher_plus: ^0.0.6
  image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/onboarding/logo.png"
  min_sdk_android: 21 
flutter:

  uses-material-design: true

  assets:
    - assets/data/
    - assets/image/
    - assets/image/onboarding/
    - assets/data/schools/
    - assets/data/schools/Babcock_University/
    - assets/data/schools/Babcock_University/Faculty/
  

 