import 'package:hive/hive.dart';

part 'simulate.g.dart'; // File generated by build_runner

@HiveType(typeId: 1)
class Simulate extends HiveObject {
  @HiveField(0)
  final double gpa;

  @HiveField(1)
  final double cgpa;

  @HiveField(2)
  final String gradingSystem;

  @HiveField(3)
  final List<dynamic> scores;

  @HiveField(4)
  final List<dynamic> courseData;

  @HiveField(5)
  final String level;

  @HiveField(6)
  final String semester;

  @HiveField(7)
  final bool uploaded;

  @HiveField(8)
  final double past_gpa;

  @HiveField(9) // Assuming this is the next available index
  final String timestamp; // Stored as a string for simplicity

  Simulate({
    required this.gpa,
    required this.cgpa,
    required this.gradingSystem,
    required this.scores,
    required this.courseData,
    required this.level,
    required this.semester,
    required this.past_gpa,
    this.uploaded = false,
    String? timestamp, // Made optional
  }) : timestamp = timestamp ??
            DateTime.now()
                .toIso8601String(); // Default to current time if not provided

  // Convert a Simulate object into a Map object
  Map<String, dynamic> toJson() => {
        'gpa': gpa,
        'cgpa': cgpa,
        'gradingSystem': gradingSystem,
        'scores': scores,
        'courseData': courseData,
        'level': level,
        'semester': semester,
        'uploaded': true,
        'past_gpa': past_gpa,
        'timestamp': timestamp,
      };

  // Create a Simulate object from a map
  factory Simulate.fromJson(Map<String, dynamic> json) => Simulate(
        gpa: json['gpa'].toDouble(),
        cgpa: json['cgpa'].toDouble(),
        gradingSystem: json['gradingSystem'],
        scores:
            json['scores'] != null ? List<dynamic>.from(json['scores']) : [],
        courseData: json['courseData'] != null
            ? List<dynamic>.from(json['courseData'])
            : [],
        level: json['level'],
        semester: json['semester'],
        past_gpa: json['past_gpa'].toDouble(),
        uploaded: json['uploaded'] ?? false,
        timestamp: json['timestamp'],
      );
  @override
  String toString() {
    return 'Simulate(gpa: $gpa, cgpa: $cgpa, gradingSystem: $gradingSystem, scores: $scores, courseData: $courseData, level: $level, semester: $semester, uploaded: $uploaded, past_gpa: $past_gpa, timestamp: $timestamp)';
  }
}
