import 'package:hive/hive.dart';
import 'package:study_stats/settings/constants.dart';

part 'user.g.dart'; // This file will be generated by Hive

@HiveType(typeId: 0) // Unique typeId for User
class User extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String name;

  @HiveField(2)
  final String email;

  @HiveField(3)
  final String password;

  @HiveField(4)
  final String matricNo; // Now required

  @HiveField(5)
  final String image; // New required field

  @HiveField(6)
  String? university;

  @HiveField(7)
  String? faculty;

  @HiveField(8)
  String? course;

  @HiveField(9)
  int? level;

  @HiveField(10)
  String? semester;

  @HiveField(11)
  double? currentCgpa;

  @HiveField(12)
  bool premium; // New non-required field with default false

  User({
    required this.id,
    required this.name,
    required this.email,
    required this.password,
    required this.matricNo,
    required this.image,
    this.university,
    this.faculty,
    this.course,
    this.level,
    this.semester,
    this.currentCgpa,
    this.premium = false, // Default value set to false
  });

  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      id: json['id'],
      name: json['name'],
      email: json['email'],
      password: json['password'],
      matricNo: json['matric_no'],
      image: json['image'],
      university: json['university'],
      faculty: json['faculty'],
      course: json['course'],
      level: json['level'],
      semester: json['semester'],
      currentCgpa: json['current_cgpa']?.toDouble(),
      premium: json['premium'] ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'email': email,
      'password': password,
      'matric_no': matricNo,
      'image': image,
      'university': university,
      'faculty': faculty,
      'course': course,
      'level': level,
      'semester': semester,
      'current_cgpa': currentCgpa,
      'premium': premium,
    };
  }

  @override
  String toString() {
    return 'User{id: $id, name: $name, email: $email, password: $password, matricNo: $matricNo, image: $image, university: $university, faculty: $faculty, course: $course, level: $level, semester: $semester, currentCgpa: $currentCgpa, premium: $premium}';
  }

  factory User.fillData(User user, Map<String, dynamic> data) {
    return User(
      id: user.id,
      name: user.name,
      email: user.email,
      password: Constants.hashPassword(user.password),
      matricNo: user.matricNo, // Updated to use user.matricNo
      image: user.image, // Updated to use user.image
      university: data['university'],
      faculty: data['faculty'],
      course: data['course'],
      level: int.parse(data['level']),
      semester: data['semester'],
      currentCgpa: double.parse(data['current_cgpa']),
      premium: data['premium'] ?? user.premium, // Updated to include premium
    );
  }
}
